const ROLES = {
  STUDENT: 1,
  USER: 2,
  INSTRUCTOR: 3,
  MODERATOR: 4,
  ADMIN: 5,
};

const STUDENT_ROLES = [
  ROLES.STUDENT,
  ROLES.USER,
  ROLES.INSTRUCTOR,
  ROLES.MODERATOR,
  ROLES.ADMIN,
];

const ADMIN_AUTHORITY = [ROLES.ADMIN, ROLES.MODERATOR, ROLES.INSTRUCTOR];
const MATERIAL_ROLES = [ROLES.INSTRUCTOR, ROLES.MODERATOR, ROLES.ADMIN];

module.exports = { ROLES, ADMIN_AUTHORITY, STUDENT_ROLES, MATERIAL_ROLES };
